apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l2solw6t5-dotnet-basic
  janus-idp.io/tekton: l2solw6t5-dotnet-basic
  backstage.io/kubernetes-id: l2solw6t5-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l2solw6t5-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
